import { DBColumnNames } from "../models/website-models";

export const LicensePlanPricing = {
  licenses: {
    month: [
      {
        name: 'Agent Seats Licenses',
        dbColumnName: DBColumnNames.AGENT_SEATS_LICENSES,
        trial: '1',
        startUp: '5',
        growth: '15',
        scale: '50',
      },
      {
        name: 'Admin Licenses',
        dbColumnName: DBColumnNames.ADMIN_LICENSES,
        trial: 'no',
        startUp: '1',
        growth: '2',
        scale: '3',
      },
      {
        name: 'Supervisor Licenses',
        dbColumnName: DBColumnNames.SUPERVISOR_LICENSES,
        trial: 'no',
        startUp: 'no',
        growth: '2',
        scale: '5',
      },
      {
        name: 'Endpoint Licenses',
        dbColumnName: DBColumnNames.END_POINT_LICENSES,
        trial: '1',
        startUp: '+$20/per',
        growth: '+$18/per',
        scale: '50 EP Included',
      },
    ],
    year: [
      {
        name: 'Agent Seats Licenses',
        dbColumnName: DBColumnNames.AGENT_SEATS_LICENSES,
        trial: '1',
        startUp: '5',
        growth: '15',
        scale: '50',
      },
      {
        name: 'Admin Licenses',
        dbColumnName: DBColumnNames.ADMIN_LICENSES,
        trial: 'no',
        startUp: '1',
        growth: '2',
        scale: '3',
      },
      {
        name: 'Supervisor Licenses',
        dbColumnName: DBColumnNames.SUPERVISOR_LICENSES,
        trial: 'no',
        startUp: 'no',
        growth: '2',
        scale: '5',
      },
      {
        name: 'Endpoint Licenses',
        dbColumnName: DBColumnNames.END_POINT_LICENSES,
        trial: '1',
        startUp: '+$20/per',
        growth: '+$18/per',
        scale: '50 EP Included',
      },
    ],
  },
  features: {
    month: [
      {
        name: 'Basic Call Handling',
        dbColumnName: DBColumnNames.BASIC_CALL_HANDLING,
        trial: 'Basic',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'Advanced Call Routing',
        dbColumnName: DBColumnNames.ADVANCED_CALL_ROUTING,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'IVR',
        dbColumnName: DBColumnNames.IVR,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'Local Presence Dialing',
        dbColumnName: DBColumnNames.LOCAL_PRESENCE_DIALING,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'Predictive Dialer',
        dbColumnName: DBColumnNames.PREDICTIVE_DIALER,
        trial: 'no',
        startUp: '$150/m',
        growth: '$120/m',
        scale: 'yes',
      },
      {
        name: 'Advanced Omnichannel',
        dbColumnName: DBColumnNames.ADVANCED_OMNI_CHANNEL,
        trial: 'no',
        startUp: '$100/channel/m',
        growth: 'Email/SMS/Chat',
        scale: 'All Channels',
      },
      {
        name: 'Ticketing Integration',
        dbColumnName: DBColumnNames.TICKETING_SYSTEM,
        trial: 'no',
        startUp: 'add-on',
        growth: 'Basic Integration',
        scale: 'Advanced Integration',
      },
      {
        name: 'Voice-to-Case',
        dbColumnName: DBColumnNames.VOICE_TO_CASE,
        trial: 'no',
        startUp: 'no',
        growth: 'no',
        scale: 'yes',
      },
      {
        name: 'Case Mangement',
        dbColumnName: DBColumnNames.CASE_MANAGEMETN,
        trial: 'Basic',
        startUp: 'Basic',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'Call Disposition Notes',
        dbColumnName: DBColumnNames.CALL_DISPOSITION_NOTES,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'Business Hours Config',
        dbColumnName: DBColumnNames.BUSINESS_HOURS_CONFIG,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'Voicemail Management',
        dbColumnName: DBColumnNames.VOICEMAIL_MANAGEMENT,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'iKunnect Intelligence',
        dbColumnName: DBColumnNames.IKUNNECT_INTELLIGENCE,
        trial: 'no',
        startUp: '$50/m',
        growth: '$100/m',
        scale: 'yes',
      },
      {
        name: 'Number Management',
        dbColumnName: DBColumnNames.NUMBER_MANAGEMENT,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'Advanced AI Automation',
        dbColumnName: DBColumnNames.ADVANCED_AI_AUTOMATION,
        trial: 'no',
        startUp: 'no',
        growth: 'no',
        scale: '$200/m',
      },
      {
        name: 'Client Branding',
        dbColumnName: DBColumnNames.CLIENT_BRANDING,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
    ],
    year: [
      {
        name: 'Basic Call Handling',
        dbColumnName: DBColumnNames.BASIC_CALL_HANDLING,
        trial: 'Basic',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'Advanced Call Routing',
        dbColumnName: DBColumnNames.ADVANCED_CALL_ROUTING,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'IVR',
        dbColumnName: DBColumnNames.IVR,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'Local Presence Dialing',
        dbColumnName: DBColumnNames.LOCAL_PRESENCE_DIALING,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'Predictive Dialer',
        dbColumnName: DBColumnNames.PREDICTIVE_DIALER,
        trial: 'no',
        startUp: '$150/m',
        growth: '$120/m',
        scale: 'yes',
      },
      {
        name: 'Advanced Omnichannel',
        dbColumnName: DBColumnNames.ADVANCED_OMNI_CHANNEL,
        trial: 'no',
        startUp: '$100/channel/m',
        growth: 'Email/SMS/Chat',
        scale: 'All Channels',
      },
      {
        name: 'Ticketing Integration',
        dbColumnName: DBColumnNames.TICKETING_SYSTEM,
        trial: 'no',
        startUp: 'add-on',
        growth: 'Basic Integration',
        scale: 'Advanced Integration',
      },
      {
        name: 'Voice-to-Case',
        dbColumnName: DBColumnNames.VOICE_TO_CASE,
        trial: 'no',
        startUp: 'no',
        growth: 'no',
        scale: 'yes',
      },
      {
        name: 'Case Mangement',
        dbColumnName: DBColumnNames.CASE_MANAGEMETN,
        trial: 'Basic',
        startUp: 'Basic',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'Call Disposition Notes',
        dbColumnName: DBColumnNames.CALL_DISPOSITION_NOTES,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'Business Hours Config',
        dbColumnName: DBColumnNames.BUSINESS_HOURS_CONFIG,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'Voicemail Management',
        dbColumnName: DBColumnNames.VOICEMAIL_MANAGEMENT,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'iKunnect Intelligence',
        dbColumnName: DBColumnNames.IKUNNECT_INTELLIGENCE,
        trial: 'no',
        startUp: '$50/y',
        growth: '$100/y',
        scale: 'yes',
      },
      {
        name: 'Number Management',
        dbColumnName: DBColumnNames.NUMBER_MANAGEMENT,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
      {
        name: 'Advanced AI Automation',
        dbColumnName: DBColumnNames.ADVANCED_AI_AUTOMATION,
        trial: 'no',
        startUp: 'no',
        growth: 'no',
        scale: '$200/y',
      },
      {
        name: 'Client Branding',
        dbColumnName: DBColumnNames.CLIENT_BRANDING,
        trial: 'no',
        startUp: 'yes',
        growth: 'yes',
        scale: 'yes',
      },
    ],
  },
};

export const PricesByDuration: {
  month: { [key: string]: { value: number; disValue: string } };
  year: { [key: string]: { value: number; disValue: string } };
} = {
  month: {
    Trial: { value: 0, disValue: '$-' },
    StartUp: { value: 500, disValue: '$500' },
    Growth: { value: 1500, disValue: '$1,500' },
    Scale: { value: 5000, disValue: '$5,000' },
  },
  year: {
    Trial: { value: 0, disValue: '$-' },
    StartUp: { value: 4500, disValue: '$4,500' },
    Growth: { value: 13500, disValue: '$13,500' },
    Scale: { value: 45000, disValue: '$45,000' },
  },
};
